protected/modules/expert/controllers/QuestionController.php
<?php

class QuestionController extends Controller {
//	public $layout='//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * @return array action filters
     */
    public function _filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * You should override this method to provide stronger access control 
     * to specifc restfull actions via AJAX
     */
    public function validateAjaxUser($action) {
        return true;
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function _accessRules() {
        return array(
//            array('allow', // allow all users to access 'index' and 'view' actions.
//                'actions' => array('index', 'view'),
//                'users' => array('*'),
//            ),
//            array('allow', // allow authenticated users to access all actions
//                'actions' => array('create'),
//                'users' => array('@'),
//            ),
            array('allow', // allow authenticated users to access all actions
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * @return array action filters
     *
      public function filters()
      {
      return array(
      'accessControl', // perform access control for CRUD operations
      );
      }

      /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     *
      public function accessRules()
      {
      return array(
      array('allow',  // allow all users to access 'index' and 'view' actions.
      'actions'=>array('index','view'),
      'users'=>array('*'),
      ),
      array('allow', // allow authenticated users to access all actions
      'users'=>array('@'),
      ),
      array('deny',  // deny all users
      'users'=>array('*'),
      ),
      );
      }

     */

    /**
     * Displays a particular model.
     */
    public function actionView($id) {
        $this->layout = 'colquest2';

//		$question = $this->loadModel($id);
        $question = Question::model()->with('author', 'аrea_expertise', 'answers', 'answerCount')->find("t.id=" . $id);
//                var_dump($question->аrea_expertise);die();
        $user = Users::model()->findByPk($question->author_id);
//		$answer=$this->newAnswer($question);

        $this->render('view', array(
            'question' => $question,
                /* 'answer'=>$answer, */
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $this->layout = 'colquest2';
        //Отсекаем незарегистрированных пользователей
        if (Yii::app()->user->isGuest) {
            Yii::app()->user->returnUrl = Yii::app()->request->requestUri;
            Yii::app()->request->redirect(Yii::app()->createAbsoluteUrl("site/login"));
        }
        $model = new Question;
//                var_dump(Yii::app()->session->isStarted);die();
        // st - шаг создания фопроса
        //st = 1  - заполняется форма
        //st = 2  - выбирается форма размещения вопроса (платно | бесплатно)
        $step = isset($_GET['st']) ? $_GET['st'] : NULL;

        if ($step !== NULL) {
            if ($step == "1") {
                $model->attributes = $_POST['Question'];
            } else if ($step == "2") {
                // Метод размещения вопроса
                $methodOfPlacingTheQuestion = isset($_POST['Question'] ["pay"]) ? $_POST['Question'] ["pay"] : FALSE;
//                        var_dump( (CUploadedFile::getInstance($model,'image')));die();
                if ($methodOfPlacingTheQuestion === FALSE && isset($_POST['Question'])) {
                    $model->attributes = $_POST['Question'];
                    $model->image = CUploadedFile::getInstance($model, 'image');
                    if ($model->save()) {
                        if ($model->image !== NULL)
                            $model->image->saveAs(Yii::app()->params['uploadDir'] . "question_img/" . $model->image->getName());
                        // Сохраняем первичный ключ вопроса для дальнейших шагов
                        $id = $model->id;
                        Yii::app()->session->writeSession("qid", $id);

                        // $this->redirect(array('view','id'=>$model->id));
                    }
                }
                elseif (in_array($methodOfPlacingTheQuestion, array("0", "1"))) {
                    switch ($methodOfPlacingTheQuestion) {
                        // Разместить вопрос бесплатно
                        case "0":
                            $model = $this->placeTheQuestionAsPaid();
                            break;
                        // Разместить вопрос платно
                        case "1":
                            $model = $this->placeTheQuestionAsFree();
                            break;
                    }
                    $this->redirect(Yii::app()->createAbsoluteUrl("question/view", array('id' => $model->id)));
                }
            }
        }

        $this->render('create', array(
            'model' => $model,
            'step' => $step,
        ));

        /*        $booking = new Booking;
          $servive = Service::model()->findByPk($id);
          $message = new Servicemessage();
          if (isset($_POST['Servicemessage'])) {
          $modelS = $this->loadModel($id);
          if ($this->checkUserBill(Yii::app()->user->id, $modelS->honorarium)) {
          $booking->userID = Yii::app()->user->id;
          $booking->expertID = $servive->expertID;
          $booking->serviceID = (int) $id;
          $booking->type = 'Услуга';
          $booking->createTime = new CDbExpression('NOW()');
          if ($booking->save(false)) {
          $message->message = $_POST['Servicemessage']['message'];
          $message->fromID = Yii::app()->user->id;
          $message->toID = $servive->expertID;
          $message->userID = Yii::app()->user->id;
          $message->createTime = new CDbExpression('NOW()');
          $message->status = 0;
          $message->bookingID = $booking->id;
          if ($message->save()) {
          $this->takeUserBill(Yii::app()->user->id, $modelS->honorarium);

          $msg = '<p style="margin-bottom: 0.14in;">
          Здравствуйте, ' . $this->getUser(Yii::app()->user->id, 'name') . ' ' . $this->getUser(Yii::app()->user->id, 'surname') . '!</p>
          <p style="margin-bottom: 0.14in;">
          Вы заказали услугу &laquo;' . $servive->notes . '&raquo;</p>
          <p style="margin-bottom: 0.14in;">
          Я приступлю к составлению вашего предсказания в самое ближайшее время.</p>
          <p style="margin-bottom: 0.14in;">
          Как только у меня будет ответ для Вас,</p>
          <p style="margin-bottom: 0.14in;">
          Уведомление о готовности заказа вы получите на на этот адрес электронной почты, который вы указали.</p>
          <p style="margin-bottom: 0.14in;">
          Всех Вам благ,</p>
          <p style="margin-bottom: 0.14in;">
          ' . $this->getUser($servive->expertID, 'profession') . ' ' . $this->getUser($servive->expertID, 'name') . '</p>
          ';
          Yii::import('application.extensions.phpmailer.JPhpMailer');
          $mail = new JPhpMailer();
          $mail->SetFrom('no-reply@magistika.com', 'magistika.com');
          $mail->Subject = 'Вы заказали услугу ' . $servive->notes . '';
          $mail->AltBody = '';
          $mail->CharSet = 'UTF-8';
          $mail->MsgHTML($msg);
          $mail->AddAddress($this->getUser(Yii::app()->user->id, 'email'), $this->getUser(Yii::app()->user->id, 'name'));
          $mail->Send();

          $this->sendMailUser($servive->expertID, 'Вам заказали услугу', 'Вам заказали услугу');

          Yii::app()->user->setFlash('booking', 'Ваш заказ принят.');
          $this->redirect(array('/service/booking/', 'id' => $id));
          }
          }
          } else {
          $this->redirect(array('/payment'));
          }
          }
          $model = new XUploadForm;


          $this->render('booking', array('model' => $model, 'booking' => $booking, 'id' => $id, 'servive' => $servive, 'message' => $message)); */
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate() {
        $model = $this->loadModel();
        if (isset($_POST['Question'])) {
            $model->attributes = $_POST['Question'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel()->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(array('index'));
        } else

protected/modules/expert/views/question/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm'); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo CHtml::errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>80,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'content'); ?>
		<?php echo CHtml::activeTextArea($model,'content',array('rows'=>10, 'cols'=>70)); ?>
		<p class="hint">You may use <a target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.</p>
		<?php echo $form->error($model,'content'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tags'); ?>
		<?php $this->widget('CAutoComplete', array(
			'model'=>$model,
			'attribute'=>'tags',
			'url'=>array('suggestTags'),
			'multiple'=>true,
			'htmlOptions'=>array('size'=>50),
		)); ?>
		<p class="hint">Please separate different tags with commas.</p>
		<?php echo $form->error($model,'tags'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status'); ?>
		<?php echo $form->dropDownList($model,'status',Lookup::items('PostStatus')); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/expert/views/question/_list.php
<?php foreach($answers as $answers): ?>
<div class="question" id="c<?php echo $question->id; ?>">

	<?php echo CHtml::link("#{$answers->id}", $answers->getUrl($question), array(
		'class'=>'cid',
		'title'=>'Permalink to this answer',
	)); ?>

	<div class="author">
		<?php echo $answer->authorLink; ?> says:
	</div>

	<div class="time">
		<?php echo date('F j, Y \a\t h:i a',$answer->create_time); ?>
	</div>

	<div class="content">
		<?php echo nl2br(CHtml::encode($answer->content)); ?>
	</div>

</div><!-- answer -->
<?php endforeach; ?>

protected/modules/expert/views/question/_view.php
<div class="post">
	<div class="title">
		<?php echo CHtml::link(CHtml::encode($data->title), $data->url); ?>
	</div>
	<div class="author">
		quested by <?php echo $data->author->username . ' on ' . date('F j, Y',$data->create_time); ?>
	</div>
	<div class="content">
		<?php
			$this->beginWidget('CMarkdown', array('purifyOutput'=>true));
			echo $data->content;
			$this->endWidget();
		?>
	</div>
	<div class="nav">
		<b>Tags:</b>
		<?php echo implode(', ', $data->tagLinks); ?>
		<br/>
		<?php echo CHtml::link('Permalink', $data->url); ?> |
		<?php echo CHtml::link("Answers ({$data->answerCount})",$data->url.'#answers'); ?> |
		Last updated on <?php echo date('F j, Y',$data->update_time); ?>
	</div>
</div>

protected/modules/expert/views/question/admin.php
<?php
//$this->breadcrumbs=array(
//	'Manage Questions',
//);
?>
<!--<h1>Manage Questions</h1>-->

<?php 
    // $this->widget('zii.widgets.grid.CGridView', array(
//	'dataProvider'=>$model->search(),
//	'filter'=>$model,
//	'columns'=>array(
//		array(
//			'name'=>'title',
//			'type'=>'raw',
//			'value'=>'CHtml::link(CHtml::encode($data->title), $data->url)'
//		),
//		array(
//			'name'=>'status',
//			'value'=>'CHtml::link(CHtml::encode($data->title), $data->url)',
//			'filter'=>Lookup::items('QuestionStatus'),
//		),
//		array(
//			'name'=>'create_time',
//			'type'=>'datetime',
//			'filter'=>false,
//		),
//		array(
//			'class'=>'CButtonColumn',
//		),
//	),
//));
?>

<div class="usercab_page">
    <div class="head">
        <h1>Вопросы потаённые</h1>
        <!--        <a href="#" class="border10 all">Сменить пароль</a>-->
    </div>
    <br />
    <br />
    <br />
    <table class="extra-mail-table">
        <tr>
            <th>Отправитель</th>
            <th class="second">Тема сообщения</th>
            <th class="last">Дата</th>
        </tr>
        <!-- Вопросы -->
        <?php
                $this->widget('zii.widgets.CListView', array(
                'dataProvider'=>$dataProvider,
                'itemView'=>'admin_item_view',   // refers to the partial view named '_post'
                'pagerCssClass' => 'pagination',
                'template' => 
                    '{items}'
                    . '<tr>'
                    . '<td colspan=3>{pager}</td>'
                    . '</tr>'
    //                'sortableAttributes'=>array(
    //                    'title',
    //                    'create_time'=>'Post Time',
    //                ),
                ));
                ?>
        <!-- Вопросы -->

    </table>

    <!--<div class="pagination">-->
        <?php
//        $this->widget('CLinkPager', array(
//            'pages' => $pages,
//            'header' => '',
//        ));
        ?>
    <!--</div>-->
</div><!-- #page -->

protected/modules/expert/views/question/admin_item_view.php
<?php $user = $data->author; ?>
<tr>
    <?php if (0): ?>
        <td>  
    <!--                        <img src="images/avatar.jpg" alt="" class="extra-avatar">-->
            (<?php // echo $cnt;  ?>) 
            <?php
//                            echo CHtml::link(
//                                    $question->author->name . '&nbsp;' . $question->author->surname,
//                                    array('question/view/', 'id' => $question->id)
//                                    ); 
            ?>
        </td>
    <?php else: ?>
        <td>  
            <?php
            echo $user->name . '&nbsp;' . $user->surname;
            ?>
        </td>
    <?php endif; ?>
    <td>
        <?php
        echo CHtml::link(
                (strlen($data->title) >= 50 ? mb_substr($data->title, 0, 50, 'UTF-8') . '...' : $data->title), Yii::app()->createAbsoluteUrl("question/view", array('id' => $data->id, '#' =>"quest-".$data->id ))
        );
        ?>
    </td>
    <td class="last">
        <?php echo Yii::app()->dateFormatter->formatDateTime($data->create_time, 'long', null); ?>
    </td>
</tr>

protected/modules/expert/views/question/index.php
<div id="questions" class="rtvs">
        <div class="info radius-5 bg-light-blue c-light-grey" >
            <ul class="list" >
                <li>- Вы можете задать <b>вопрос онлайн бесплатно</b> сразу всем экпертам.</li>
                <li>- Ваши личныйе даные и фотографии доступны для просмотра, только эксертам</li>
                <li>- Вы можете <b>задать вопрос ясновидящим</b>, оставаясь инкогнито без публикации на сайте</li>
            </ul>    
            
            <div class="form question">
                <?php 
                    $form = $this->beginWidget('CActiveForm', array(
                        'action' => Yii::app()->createUrl('question/create', array('st' => Question::STATUS_DRAFT)),
                    )); 
                ?>
                    <div class="row">
                        <?php 
                            echo $form->textField(
                                $model, 
                                'title', 
                                array(
                                    'class' => 'quest-text radius-5',
                                    'placeholder' => "Введите ваш вопрос",
                                    )
                                );
                        ?>
                        <?php echo $form->error($model,'title'); ?>
                        <?php echo CHtml::submitButton("Отправить", array('class' => 'quest-sub bg-fiolet radius-5'));?>
                    </div>
                <?php $this->endWidget();?>
                <?php
                /* $form=$this->beginWidget('CActiveForm'); ?>

                <?/*<p class="note">Fields with <span class="required">*</span> are required.</p>?>

                <?php echo CHtml::errorSummary($model); ?>

                    <div class="row">
                       <?php echo $form->labelEx($model,'title'); ?>
                       <?php echo $form->textField($model,'title',array('size'=>80,'maxlength'=>128)); ?>
                       <?php echo $form->error($model,'title'); ?>
                  </div>
                  <div class="row buttons">
                        <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
                  </div>

                <?php $this->endWidget(); */?>

                <!-- form -->
            </div>    
        </div>                      
        <div id="tabs-question" class="list-view question bg-light-ellow radius-5" >
            <ul class="tabs-menu c-light-grey tr-upper" >Последние вопросы
                    <li class="fr p-l10 tr-none" ><a href="#ui-tabs-1">Платные</a></li> 
                    <li class="fr tr-none"><a href="#ui-tabs-2">Бесплатные</a></li> 
            </ul>
            <div id="ui-tabs-1" class="tab-pay-quest" >
                <?php for ($i=0;$i<8;$i++) { ?>
                <div id="quest-<?php echo $i;?>" class="item-quest">
                    <div class="pic-quest fl" >
                        <a href="#" title="Переход на страницу пользователя" class="info-user" >
                            <img src="/images/avatar-quester.png" title="Картинка пользователя" valign='top' />
                        </a> 
                    </div>
                    <div class="info-quest ff-tahoma" >
                        <h3>
                            <a href="#" class="title fs-16 c-fiolet" >Когда я выйду замуж?</a>
                        </h3>
                        <p class="desc-quest c-green-grey fs-13" >
                            Как сделать так, чтоб не дойти до критической ситуации в семье? Самые просты правила. Как сделать так, чтоб не дойти до читать далее...
                        </p>
                        <div class="icons-quest fs ff-tahoma fs-12" >
                            <div class="date-quest fl" >2 ноября 2013</div>
                            <div class="maps-taro-quest fl" >Карты тарро</div>
                            <div class="answers-quest fl" >Ответов(20)</div>
                            <div class="clear"></div>
                        </div>
                    </div>                    
                </div>  
               <?php }?> 
               <!-- пагинация --> 
               <center class="m-b14">
                    <div class="pager"><?php /*Перейти к странице:*/?>
                        <ul class="yiiPager" id="yw4">
                             <li class="first hidden"><a href="/ru/site/index.html">&lt;&lt; First</a></li>
                             <li class="previous <?php //hidden;?>"><a href="/ru/site/index.html">&lt; Вперед</a></li>
                             <li class="page selected"><a href="/ru/site/index.html">1</a><span >|</span></li>
                             <li class="page"><a href="/ru/site/index.html?page=2">2</a><span>|</span></li>
                             <li class="page"><a href="/ru/site/index.html?page=3">3</a><span>|</span></li>
                             <li class="page"><a href="/ru/site/index.html?page=4">4</a><span>|</span></li>
                             <li class="page"><a href="/ru/site/index.html?page=5">5</a><span>|</span></li>
                             <li class="page"><a href="/ru/site/index.html?page=6">6</a></li>
                             <li class="next"><a href="/ru/site/index.html?page=2">Назад &gt;</a></li>
                             <li class="last"><a href="/ru/site/index.html?page=6">Last &gt;&gt;</a></li>
                         </ul>
                     </div>
               </center>                
            </div>
            <div id="ui-tabs-2" class="tab-nopay-quest">
                <?php for ($i=0;$i<7;$i++) { ?>
                <div id="quest-1<?=$i;?>" class="item-quest">
                    <div class="pic-quest fl" >
                        <a href="#" title="Переход на страницу пользователя" class="info-user" >
                            <img src="/images/avatar-quester.png" title="Картинка пользователя" valign='top' />
                        </a> 
                    </div>
                    <div class="info-quest ff-tahoma" >
                        <h3>
                            <a href="#" class="title fs-16 c-fiolet" >Когда я выйду замуж?</a>
                        </h3>
                        <p class="desc-quest c-green-grey fs-13" >
                            Как сделать так, чтоб не дойти до критической ситуации в семье? Самые просты правила. Как сделать так, чтоб не дойти до читать далее...
                        </p>
                        <div class="icons-quest fs ff-tahoma fs-12" >
                            <div class="date-quest fl" >2 ноября 2013</div>
                            <div class="maps-taro-quest fl" >Карты тарро</div>
                            <div class="answers-quest fl" >Ответов(20)</div>
                            <div class="clear"></div>
                        </div>
                    </div>                    
                </div>
               <?php}?>
               <!-- пагинация --> 
               <center class="m-b14">
                    <div class="pager"><?php/*Перейти к странице:*/?>
                        <ul class="yiiPager" id="yw4">
                             <li class="first hidden"><a href="/ru/site/index.html">&lt;&lt; First</a></li>
                             <li class="previous <?php hidden;?>"><a href="/ru/site/index.html">&lt; Вперед</a></li>
                             <li class="page selected"><a href="/ru/site/index.html">1</a></li>
                             <li class="page"><a href="/ru/site/index.html?page=2">2</a></li>
                             <li class="page"><a href="/ru/site/index.html?page=3">3</a></li>
                             <li class="page"><a href="/ru/site/index.html?page=4">4</a></li>
                             <li class="page"><a href="/ru/site/index.html?page=5">5</a></li>
                             <li class="page"><a href="/ru/site/index.html?page=5">5</a></li>
                             <li class="next"><a href="/ru/site/index.html?page=2">Назад &gt;</a></li>
                             <li class="last"><a href="/ru/site/index.html?page=5">Last &gt;&gt;</a></li>
                         </ul>
                     </div>
               </center>  
            </div> 
            
        <?php 
                /* if(!empty($_GET['tag'])): ?>
                <h1>Questions Tagged with <i><?php echo CHtml::encode($_GET['tag']); ?></i></h1>
                <?php endif; ?>

                /*$this->widget('zii.widgets.CListView', array(
                    'dataProvider'=>$dataProvider,
                    'itemView'=>'_view',
                    'template'=>"{items}\n{pager}",
                ));*/ 
        ?>
            
        </div>
        <script>
            // Tabs
            $("#tabs-question").tabs({hide: {effect: "fadeOut", duration: 100},collapsible: true});
        </script>
</div>

protected/modules/expert/views/question/update.php
<?php
$this->breadcrumbs=array(
	$model->title=>$model->url,
	'Update',
);
?>

<h1>Update <i><?php echo CHtml::encode($model->title); ?></i></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/expert/views/question/view.php
<?php
/*$this->breadcrumbs=array(
	$model->title,
);
$this->pageTitle=$model->title;*/
?>

<?php
/* $this->renderPartial('_view', array(
	'data'=>$model,
)); */?>

<?php $this->renderPartial('/site/_sliderbox'); ?>

<div id="question" class="m-t380">
    <div class="form bg-grey radius-5">
        <form> 
            <input type="button" value="Задать вопрос онлайн" class="button ask" />
            <input type="button" value="Просмотреть все вопросы" class="button view" />
        </form>
    </div>
    <div class="about bg-light-ellow radius-10" >
        <div id="quest-<?php echo $question->id;?>" class="item m-0">
            <div class="pic fl" >
               <a href="#" title="Переход на страницу пользователя" class="info-user" >
                  <img src="/images/avatar-quester.png" title="Картинка пользователя" valign='top' />
               </a> 
            </div>
            <div class="info ff-tahoma" >
                <h3>
                   <a href="#" class="title fs-16 c-fiolet" ><?php echo CHtml::encode($question->title);?></a>
                </h3>
                <p class="desc c-green-grey fs-13" >
                    <?php echo CHtml::encode($question->content);?>
                </p>
                <div class="user ff-tahoma fs-12" >
                    <div class="name p-0 fl" >Автор вопроса:&nbsp;<span><?php echo $question->author->name; ?></span><span>&nbsp;|&nbsp;</span></div>
                   <div class="date p-0 fl" >
                       <?php 
//                     var_dump( $question->create_time);
//                     Yii::app()->dateFormatter->format(Question::DATE_TIME_FORMAT, $question->create_time);
//                            $dt = new DateTime($question->create_time);
                        echo Yii::app()->dateFormatter->format("dd MM yyyy", $question->create_time);
                        
                        ?>
                       <span>&nbsp;|&nbsp;</span>
                   </div> 
                   <div class="clear"></div>
                 </div>
             </div>                    
        </div>        
    </div>
    <div id="quest-answers">
        <h3><span class="title">Ответы экспертов</span> <span class="section">Категория: <?php echo $question->аrea_expertise->name; ?></span></h3>
        <?php for ($a=0;$a<5;$a++) :?>
        <div id="answer-<?//=$a;?>" class="item answer ">
            <div class="pic expert fl" >
               <a href="#" title="Переход на страницу пользователя" class="link expert" >
                  <img src="/images/avatar-expert.png" title="Картинка експерта" valign='top' />
               </a> 
            </div>
            <div class="info expert ff-tahoma" >
                <div class="name">
                   <a href="#" class="link expert fs-16 c-fiolet" >Ольга</a>
                </div>
                <div class="about">
                    <div class="status">
                        <div class="short">
                            <span class="prof">Гадание на картах</span>
                            <span class="stat">online</span>
                        </div>
                        <div class="ratting">
                            <div class="rat fl"></div>
                            <div class="rat fl"></div>
                            <div class="rat fl"></div>
                            <div class="rat fl"></div>
                            <div class="rat fl"></div>
                            <div class="cnt">11743</div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="sub form">
                        <form>
                            <input type="submit" value="Написать" class="button write" />
                        </form>                            
                    </div>
                    <div class="clear"></div>
                </div>
                <p class="desc answer c-green-grey fs-13" >
                   Здравствуйте эксперты. Скажите сколько в моей судьбе официальных браков - сколько уже было и сколько будет в будущем и сколько по судьбе детей по возможности когда родятся. выйду ли замуж в ближайшие 2 года.
                </p>
            </div>                    
        </div>  
        <?php endfor; ?>
            <?php
            /* if($model->questionCount>=1): ?>
                    <h3>
                            <?php echo $model->questionCount>1 ? $model->questionCount . ' questions' : 'One question'; ?>
                    </h3>

                    <?php $this->renderPartial('_list',array(
                            'post'=>$model,
                            'questions'=>$model->questions,
                    )); ?>
            <?php endif; ?>

            <h3>Leave a Question</h3>

            <?php if(Yii::app()->user->hasFlash('questionSubmitted')): ?>
                    <div class="flash-success">
                            <?php echo Yii::app()->user->getFlash('questionSubmitted'); ?>
                    </div>
            <?php else: ?>
                    <?php $this->renderPartial('/question/_form',array(
                            'model'=>$question,
                    )); ?>
            <?php endif; */?>

    </div><!-- questions -->
</div>